use jobs.if for roll up a,b

diff --git a/.github/workflows/test-workflows.yml b/.github/workflows/test-workflows.yml
--- a/.github/workflows/test-workflows.yml
+++ b/.github/workflows/test-workflows.yml
@@ -27,23 +27,24 @@ jobs:
   roll-up-a:
     needs: [a-shard]
     runs-on: ubuntu-latest
-    if: ${{ !cancelled() }}
+    if: ${{ failure() }}
     steps:
-      - run: echo a-shard-result=${{ needs.a-shard.result }}
-      - if: success()
-        run: echo "success"
-      - if: cancelled()
-        run: echo "cancelled"
-      - if: always()
-        run: echo "always"
-      - if: ${{ needs.a-shard.result == 'failure' }}
-        run: |
-          echo "failing because b-shard failed"
-          exit 1
-      - if: failure()
-        run: |
-          echo "failure"
-          exit 1
+      - run: echo "a-shard failed" && exit 1
+      # - run: echo a-shard-result=${{ needs.a-shard.result }}
+      # - if: success()
+      #   run: echo "success"
+      # - if: cancelled()
+      #   run: echo "cancelled"
+      # - if: always()
+      #   run: echo "always"
+      # - if: ${{ needs.a-shard.result == 'failure' }}
+      #   run: |
+      #     echo "failing because b-shard failed"
+      #     exit 1
+      # - if: failure()
+      #   run: |
+      #     echo "failure"
+      #     exit 1
 
   a-shard-did-fail:
     needs: [a-shard]
@@ -63,23 +64,24 @@ jobs:
   roll-up-b:
     needs: [b-shard]
     runs-on: ubuntu-latest
-    if: ${{ !cancelled() }}
+    if: ${{ failure() }}
     steps:
-      - run: echo b-shard-result=${{ needs.b-shard.result }}
-      - if: success()
-        run: echo "success"
-      - if: cancelled()
-        run: echo "cancelled"
-      - if: always()
-        run: echo "always"
-      - if: ${{ needs.b-shard.result == 'failure' }}
-        run: |
-          echo "failing because b-shard failed"
-          exit 1
-      - if: failure()
-        run: |
-          echo "failure"
-          exit 1
+      - run: echo "b-shard failed" && exit 1
+      # - run: echo b-shard-result=${{ needs.b-shard.result }}
+      # - if: success()
+      #   run: echo "success"
+      # - if: cancelled()
+      #   run: echo "cancelled"
+      # - if: always()
+      #   run: echo "always"
+      # - if: ${{ needs.b-shard.result == 'failure' }}
+      #   run: |
+      #     echo "failing because b-shard failed"
+      #     exit 1
+      # - if: failure()
+      #   run: |
+      #     echo "failure"
+      #     exit 1
 
   b-shard-did-fail:
     needs: [b-shard]
