comment out step-status check

diff --git a/.github/workflows/test-workflows.yml b/.github/workflows/test-workflows.yml
--- a/.github/workflows/test-workflows.yml
+++ b/.github/workflows/test-workflows.yml
@@ -27,20 +27,20 @@ jobs:
           echo "fail_b_number=" >> "$GITHUB_OUTPUT"
       - run: sleep 3
 
-  test-step-status:
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo hi
-      - if: success()
-        run: echo "this runs because all prev steps in this job succeeded"
-      - run: exit 1
-      - if: failure()
-        run: echo "this will run because some prev step failed"
-      - if: always()
-        run: echo "this runs too"
-      - if: success()
-        run: echo "this does not run bc a prev step failed"
-      - run: echo "this does not run either bc a prev step failed"
+  # test-step-status:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: echo hi
+  #     - if: success()
+  #       run: echo "this runs because all prev steps in this job succeeded"
+  #     - run: exit 1
+  #     - if: failure()
+  #       run: echo "this will run because some prev step failed"
+  #     - if: always()
+  #       run: echo "this runs too"
+  #     - if: success()
+  #       run: echo "this does not run bc a prev step failed"
+  #     - run: echo "this does not run either bc a prev step failed"
 
   a-shard:
     runs-on: ubuntu-latest
