roll up all reflects result

diff --git a/.github/workflows/test-workflows.yml b/.github/workflows/test-workflows.yml
--- a/.github/workflows/test-workflows.yml
+++ b/.github/workflows/test-workflows.yml
@@ -95,11 +95,7 @@ jobs:
     steps:
       - run: echo rollup-a-result=${{ needs.roll-up-a.result }}
       - run: echo rollup-b-result=${{ needs.roll-up-b.result }}
-      - if: failure()
-        run: echo "failure"
-      - if: success()
-        run: echo "success"
-      - if: cancelled()
-        run: echo "cancelled"
-      - if: always()
-        run: echo "always"
+      - if: ${{ needs.roll-up-a.result == 'failure' }}
+        run: echo "a failed" && exit 1
+      - if: ${{ needs.roll-up-b.result == 'failure' }}
+        run: echo "b failed" && exit 1
