test step statuses

diff --git a/.github/workflows/test-workflows.yml b/.github/workflows/test-workflows.yml
--- a/.github/workflows/test-workflows.yml
+++ b/.github/workflows/test-workflows.yml
@@ -27,6 +27,19 @@ jobs:
           echo "fail_b_number=" >> "$GITHUB_OUTPUT"
       - run: sleep 3
 
+  test-step-status:
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo hello
+      - if: success()
+        run: "success runs bc nothing has failed yet"
+      - run: exit 1
+      - if: always()
+        run: echo "always runs"
+      - if: failure()
+        run: echo "failure runs"
+      - run: echo "does not run because failure"
+
   a-shard:
     runs-on: ubuntu-latest
     needs: [configure]
