simplify

diff --git a/.github/workflows/test-rollup-jobs.yml b/.github/workflows/test-rollup-jobs.yml
--- a/.github/workflows/test-rollup-jobs.yml
+++ b/.github/workflows/test-rollup-jobs.yml
@@ -5,6 +5,7 @@ on:
     branches: [main, master]
 
 jobs:
+  # always times out
   timeout-job:
     runs-on: ubuntu-latest
     timeout-minutes: 1
@@ -14,13 +15,19 @@ jobs:
         run: |
           sleep 90
 
+  # this rollup job shows that "cancelled()" works counter-intuitively.
+  # Even though the dependent job timed out and was cancelled,
+  # this job is skipped (because `cancelled()` refers to this job's status, so it is not `true`)
   timeout-job-incorrect-result:
     runs-on: ubuntu-latest
     needs: timeout-job
-    if: ${{ failure() || cancelled() }}
+    if: ${{ cancelled() }}
     steps:
       - run: exit 1
 
+  # this rollup job correctly checks the status of the dependent job.
+  # this job runs "always" but fails ('exit 1') if `needs.tieout-job.result` is
+  # a failure or cancelled (ie "not success")
   timeout-job-correct-result:
     runs-on: ubuntu-latest
     needs: timeout-job
@@ -29,11 +36,14 @@ jobs:
       - if: ${{ needs.timeout-job.result != 'success' }}
         run: exit 1
 
+  # This job always fails
   failure-job:
     runs-on: ubuntu-latest
     steps:
       - run: exit 1
 
+  # This rollup job shows that `if failure()` works as we expect, unlike `if cancelled()`:
+  # it is "true" bc the dependent job failed
   failure-job-result:
     runs-on: ubuntu-latest
     needs: failure-job
@@ -41,21 +51,8 @@ jobs:
     steps:
       - run: exit 1
 
-  failure-job-robust-result:
-    runs-on: ubuntu-latest
-    needs: failure-job
-    if: ${{ always() }}
-    steps:
-      - if: ${{ needs.failure-job.result != 'success' }}
-        run: exit 1
-
-  rollup-job-incorrect-result:
-    runs-on: ubuntu-latest
-    needs: [failure-job, timeout-job]
-    if: ${{ failure() || cancelled() }}
-    steps:
-      - run: exit 1
-
+  # This rollup job depends on both the failure and timeout jobs.
+  # It uses the robust technique of always running and checking the result of the dependent job(s)
   rollup-job-correct-result:
     runs-on: ubuntu-latest
     needs: [failure-job, timeout-job]
