add dependent steps

diff --git a/.github/workflows/test-workflows.yml b/.github/workflows/test-workflows.yml
--- a/.github/workflows/test-workflows.yml
+++ b/.github/workflows/test-workflows.yml
@@ -1,7 +1,70 @@
 on:
-  pull_request: 
+  pull_request:
 jobs:
   configure:
     runs-on: ubuntu-latest
     steps:
       - run: echo "hello"
+      - run: echo "hello again"
+
+  a-shard:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        number: [1, 2]
+    steps:
+      - run: echo ${{ matrix.number }}
+
+  roll-up-a:
+    needs: [a-shard]
+    runs-on: ubuntu-latest
+    if: ${{ !cancelled() }}
+    steps:
+      - if: success()
+        run: echo "success"
+      - if: cancelled()
+        run: echo "cancelled"
+      - if: always()
+        run: echo "always"
+      - if: failure()
+        run: |
+          echo "failure"
+          exit 1
+
+  b-shard:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        number: [1, 2]
+    steps:
+      - run: echo ${{ matrix.number }}
+
+  roll-up-b:
+    needs: [b-shard]
+    runs-on: ubuntu-latest
+    if: ${{ !cancelled() }}
+    steps:
+      - if: success()
+        run: echo "success"
+      - if: cancelled()
+        run: echo "cancelled"
+      - if: always()
+        run: echo "always"
+      - if: failure()
+        run: |
+          echo "failure"
+          exit 1
+
+  roll-up-all:
+    runs-on: ubuntu-latest
+    needs: [roll-up-a, roll-up-b]
+    if: ${{ !cancelled() }}
+    steps:
+      - if: failure()
+        run: echo "failure"
+      - if: success()
+        run: echo "success"
+      - if: cancelled()
+        run: echo "cancelled"
+      - if: always()
+        run: echo "always"
